### ISSUE TITLE
Project Checkpoint 1

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jskarha/JavaEESemesterProject#1]
Hi Justin,

I'm sorry I ran out of time last night to review your indie project work to date. You have a solid project idea here and it looks like you've put some good thought out the technologies you'll be using (particularly the web services/apis and independent research topic). 

The screens you have so far look good, what additional screens will you have? I'm assuming there will be more?

A few items seem to missing though, or did I overlook them somehow?

- [x] Project Plan
- [x] Application flow
- [x] Time log

**Comment by jskarha** [comment]
I apologize for the delay, I have added the listed items. As for more screens, there will be a decklist display screen, a user home screen, a search results screen, and an about screen. (i think? some of this is still pretty fuzzy, hence the lack of pictures)
